<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>hadoop-tools</artifactId>
        <groupId>org.apache.hadoop</groupId>
        <version>2.6.0-mdh3.12.5-jre8</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.xiaomi.infra</groupId>
    <artifactId>scribe-merger</artifactId>
    <packaging>jar</packaging>
    <description>Scribe Files Merge Tool</description>
    <name>Scribe Files Merge Tool</name>

    <dependencies>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-client</artifactId>
            <version>2.6.0-mdh3.12.5-jre8</version>
        </dependency>
        <dependency>
            <groupId>org.apache.mrunit</groupId>
            <artifactId>mrunit</artifactId>
            <version>1.0.0</version>
            <type>jar</type>
            <classifier>hadoop2</classifier>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
