<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License. See accompanying LICENSE file.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.apache.hadoop</groupId>
    <artifactId>hadoop-project_1.8</artifactId>
    <version>2.6.0-mdh3.9.0</version>
    <relativePath>../hadoop-project</relativePath>
  </parent>
  <groupId>org.apache.hadoop</groupId>
  <artifactId>hadoop-dist_1.8</artifactId>
  <version>2.6.0-mdh3.9.0</version>
  <description>Apache Hadoop Distribution</description>
  <name>Apache Hadoop Distribution</name>
  <packaging>jar</packaging>

  <!-- Using dependencies to ensure this module is the last one -->
  <dependencies>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-security_1.8</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-common_1.8</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-hdfs_1.8</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-mapreduce-client-app_1.8</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-yarn-api_1.8</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <properties>
    <hdfs.raid>false</hdfs.raid>
  </properties>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-deploy-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.rat</groupId>
        <artifactId>apache-rat-plugin</artifactId>
        <configuration>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>raid</id>
      <activation>
        <activeByDefault>false</activeByDefault>
      </activation>
      <properties>
        <hdfs.raid>true</hdfs.raid>
      </properties>
    </profile>
    <profile>
      <id>dist</id>
      <activation>
        <activeByDefault>false</activeByDefault>
        <property>
          <name>tar|rpm|deb</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-antrun-plugin</artifactId>
            <executions>
              <execution>
                <id>dist</id>
                <phase>prepare-package</phase>
                <goals>
                  <goal>run</goal>
                </goals>
                <configuration>
                  <target>
                    <echo file="${project.build.directory}/dist-layout-stitching.sh">
                      run() {
                        echo "\$ ${@}"
                        "${@}"
                        res=$?
                        if [ $res != 0 ]; then
                          echo
                          echo "Failed!"
                          echo
                          exit $res
                        fi
                      }

                      cp_hdfs_raid() {
                        echo run cp_hdfs_raid
                        if [ ${hdfs.raid} = true ]; then
                        run cp -r $ROOT/hadoop-hdfs-project/hadoop-hdfs/src/contrib/raid/target/hadoop-hdfs-raid${java.suffix}-${project.version}/* .
                        fi
                      }

                      ROOT=`cd ../..;pwd`
                      echo
                      echo "Current directory `pwd`"
                      echo
                      run rm -rf hadoop-${project.version}${java.tar.suffix}
                      run mkdir hadoop-${project.version}${java.tar.suffix}
                      run cd hadoop-${project.version}${java.tar.suffix}
                      run cp $ROOT/LICENSE.txt .
                      run cp $ROOT/NOTICE.txt .
                      run cp $ROOT/README.txt .
                      run cp -r $ROOT/hadoop-common-project/hadoop-common/target/hadoop-common${java.suffix}-${project.version}/* .
                      run cp -r $ROOT/hadoop-common-project/hadoop-nfs/target/hadoop-nfs${java.suffix}-${project.version}/* .
                      run cp -r $ROOT/hadoop-hdfs-project/hadoop-hdfs/target/hadoop-hdfs${java.suffix}-${project.version}/* .
                      run cp -r $ROOT/hadoop-hdfs-project/hadoop-hdfs-httpfs/target/hadoop-hdfs-httpfs${java.suffix}-${project.version}/* .
                      run cp -r $ROOT/hadoop-common-project/hadoop-kms/target/hadoop-kms${java.suffix}-${project.version}/* .
                      run cp -r $ROOT/hadoop-hdfs-project/hadoop-hdfs-nfs/target/hadoop-hdfs-nfs${java.suffix}-${project.version}/* .
                      run cp -r $ROOT/hadoop-yarn-project/target/hadoop-yarn-project${java.suffix}-${project.version}/* .
                      run cp -r $ROOT/hadoop-mapreduce-project/target/hadoop-mapreduce${java.suffix}-${project.version}/* .
                      run cp -r $ROOT/hadoop-tools/hadoop-tools-dist/target/hadoop-tools-dist${java.suffix}-${project.version}/* .
                      run cp $ROOT/hadoop-common-project/hadoop-security/target/hadoop-security${java.suffix}-${project.version}.jar ./share/hadoop/common/lib/
                      run cp_hdfs_raid
                      echo
                      echo "Hadoop dist layout available at: ${project.build.directory}/hadoop-${project.version}${java.tar.suffix}"
                      echo
                    </echo>
                    <exec executable="sh" dir="${project.build.directory}" failonerror="true">
                      <arg line="./dist-layout-stitching.sh"/>
                    </exec>
                  </target>
                </configuration>
              </execution>
              <execution>
                <id>tar</id>
                <phase>package</phase>
                <goals>
                  <goal>run</goal>
                </goals>
                <configuration>
                  <target if="tar">
                    <echo file="${project.build.directory}/dist-tar-stitching.sh">
                      run() {
                        echo "\$ ${@}"
                        "${@}"
                        res=$?
                        if [ $res != 0 ]; then
                          echo
                          echo "Failed!"
                          echo
                          exit $res
                        fi
                      }

                      run tar cf hadoop-${project.version}${java.tar.suffix}.tar hadoop-${project.version}${java.tar.suffix}
                      run gzip -f hadoop-${project.version}${java.tar.suffix}.tar
                      echo
                      echo "Hadoop dist tar available at: ${project.build.directory}/hadoop-${project.version}${java.tar.suffix}.tar.gz"
                      echo
                    </echo>
                    <exec executable="sh" dir="${project.build.directory}" failonerror="true">
                      <arg line="./dist-tar-stitching.sh"/>
                    </exec>
                  </target>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>
